version: '3.8'


services:
  gpt-sovits:
    build: .
    container_name: gpt-sovits-container
    environment:
      - is_half=False
      - is_share=False
      - workers=1
      - port=8828
    volumes:
      - ../storage/pretrained_models:/workspace/GPT_SoVITS/pretrained_models
      - ../storage/G2PWModel:/workspace/GPT_SoVITS/text/G2PWModel
      - ../storage/pip:/root/.cache/pip
      - ../storage/venv:/venv
      - ../storage/nltk_data:/root/nltk_data
      - ../storage/uploads:/uploads
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8828:8828"
    shm_size: 16G
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: "all"
    #         capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: unless-stopped
